require 'ffi-compiler/compile_task'

FFI::Compiler::CompileTask.new('ruby-tls-ext') do |t|
    t.cflags << "-Wall -Wextra -O3"
    t.cflags << "-D_GNU_SOURCE=1" if RbConfig::CONFIG["host_os"].downcase =~ /mingw/
    t.cflags << "-arch x86_64 -arch i386" if t.platform.mac?
    t.ldflags << "-arch x86_64 -arch i386" if t.platform.mac?

    # Link to OpenSSL
    if FFI::Platform.windows?
        path = File.dirname(ENV["OPENSSL_CONF"])
        path = File.expand_path("../", path)
        t.cflags << "-I \"#{path}/include\""
        t.ldflags << "-L\"#{path}/lib\" -lssleay32 -llibeay32"
    else
        t.ldflags << "-lssl -lcrypto"
    end
end
