require 'ffi-compiler/compile_task'

FFI::Compiler::CompileTask.new('ruby-tls-ext') do |t|
    t.cflags << "-Wall -Wextra -O3"
    t.cflags << "-D_GNU_SOURCE=1" if RbConfig::CONFIG["host_os"].downcase =~ /mingw/
    t.cflags << "-arch x86_64 -arch i386" if t.platform.mac?
    t.ldflags << "-arch x86_64 -arch i386" if t.platform.mac?

    # Link to OpenSSL
    if FFI::Platform.windows?
        if FFI::Platform::ARCH == 'i386'
            t.cflags << "-I c:/OpenSSL-Win32/include"
            t.ldflags << '-L"c:/OpenSSL-Win32/lib" -lssleay32 -llibeay32'
        else
            t.cflags << "-I c:/OpenSSL-Win64/include"
            t.ldflags << '-L"c:/OpenSSL-Win64/lib" -lssleay32 -llibeay32'
        end
    else
        t.ldflags << "-lssl -lcrypto"
    end
end
